FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

# Install dependencies including DVC and Git
RUN apt-get update && apt-get install -y git && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir dvc

COPY . .

EXPOSE 8000

CMD ["uvicorn", "api_server:app", "--host", "0.0.0.0", "--port", "8000"]
