version: '3.9'

services:

  tester:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    depends_on:
      - api
    container_name: test-client
    restart: on-failure
version: '3.8'

mlflow:
  build:
    context: .
    dockerfile: Dockerfile.mlflow
  ports:
    - "5000:5000"
  volumes:
    - ./mlruns:/mlflow/mlruns
  environment:
    - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
    - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/mlruns
  command: mlflow server \
    --backend-store-uri=sqlite:///mlflow.db \
    --default-artifact-root=/mlflow/mlruns \
    --host 0.0.0.0 \
    --port 5000

fastapi:
  build:
    context: .
    dockerfile: Dockerfile.api
  ports:
    - "8000:8000"
  depends_on:
    - mlflow
  env_file:
    - .env
  command: ["sh", "entrypoint.sh"]
