stages:
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw/titanic.csv
    - src/data_preprocessing.py
    outs:
    - data/processed/titanic_preprocessed/processed_test.parquet
    - data/processed/titanic_preprocessed/processed_train.parquet
  baseline_stats:
    cmd: python src/baseline_stats.py
    deps:
    - data/processed/titanic_preprocessed/processed_train.parquet
    - src/baseline_stats.py
    outs:
    - data/baseline_stats.json
  train_model:
    cmd: python src/train_model.py
    deps:
    - data/processed/titanic_preprocessed/processed_train.parquet
    - params.yaml
    - src/train_model.py
    outs:
    - models/logistic_model
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/processed/titanic_preprocessed/processed_test.parquet
    - models/logistic_model
    - src/evaluate.py
    outs:
    - outputs/classification_report.csv
    - outputs/confusion_matrix.png
  simulate_drift:
    cmd: python src/simulate_drift.py
    deps:
    - data/processed/titanic_preprocessed/processed_test.parquet
    - src/simulate_drift.py
    outs:
    - data/drifted/test_drifted.parquet
  drift_detection:
    cmd: python src/drift_detection.py
    deps:
    - data/baseline_stats.json
    - data/drifted/test_drifted.parquet
    - src/drift_detection.py
    outs:
    - outputs/drift_report.json
