stages:
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw/train.csv
    - params.yaml
    - src/data_preprocessing.py
    outs:
    - data/processed/titanic_preprocessed/processed_train.parquet:
        cache: false
  baseline_stats:
    cmd: python src/baseline_stats.py
    deps:
    - data/processed/titanic_preprocessed/processed_train.parquet
    - params.yaml
    - src/baseline_stats.py
    outs:
    - data/baseline_stats/baseline_stats.json:
        cache: false
  train_model:
    cmd: python src/train_model.py
    deps:
    - data/processed/titanic_preprocessed/processed_train.parquet
    - params.yaml
    - src/train_model.py
    outs:
    - models/best_model:
        cache: false
  simulate_drift:
    cmd: python src/simulate_drift.py
    deps:
    - params.yaml
    - src/simulate_drift.py
    outs:
    - data/processed/titanic_preprocessed_drifted/:
        cache: false
  drift_detection:
    cmd: python src/drift_detection.py
    deps:
    - data/baseline_stats/baseline_stats.json
    - data/processed/titanic_preprocessed_drifted/
    - params.yaml
    - src/drift_detection.py
    outs:
    - report/drift_report.json:
        cache: false
  retrain:
    cmd: python src/automated_retrain.py
    deps:
    - data/raw/train.csv
    - params.yaml
    - report/drift_report.json
    - src/automated_retrain.py
    - src/data_preprocessing.py
    - src/drift_detection.py
    - src/train_model.py
    outs:
    - report/retrain_drift_report.json:
        cache: false
